services:
    billing.admin.client:
        class: BillingBundle\Admin\ClientAdmin
        arguments: [~, BillingBundle\Entity\Client, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "admin.menu.group.admin"
              label: "admin.menu.group.item.clients"

    billing.admin.instructor:
        class: BillingBundle\Admin\InstructorAdmin
        arguments: [~, BillingBundle\Entity\Instructor, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "admin.menu.group.admin"
              label: "admin.menu.group.item.instructors"

    billing.admin.service:
        class: BillingBundle\Admin\ServiceAdmin
        arguments: [~, BillingBundle\Entity\Service, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "admin.menu.group.admin"
              label: "admin.menu.group.item.services"

    billing.admin.plan:
        class: BillingBundle\Admin\PlanAdmin
        arguments: [~, BillingBundle\Entity\Plan, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: "admin.menu.group.admin"
              label: "admin.menu.group.item.plans"

    billing.admin.client_plan:
        class: BillingBundle\Admin\ClientPlanAdmin
        arguments: [~, BillingBundle\Entity\ClientPlan, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: ClientPlan }
