<?php

namespace BillingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClientPlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientPlanRepository extends EntityRepository
{
}
