<?php

namespace BillingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstructorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstructorRepository extends EntityRepository
{
}
