<?php

namespace BillingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InstructorTrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstructorTrainingRepository extends EntityRepository
{
}
