<?php

namespace BillingBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingInstructorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingInstructorRepository extends EntityRepository
{
}
